spring:
  application.name: "kiting-chat-ai-host"
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  ai:
    ollama:
      base-url: http://localhost:11431
      chat.model: PetrosStav/gemma3-tools:4b
    mcp:
      client:
        name: "mcp-client"
        version: 1.0.0
        type: sync
        streamable-http:
          connections:
            mcp-server:
              url: http://localhost:8081/mcp
              endpoint: /mcp

chat:
  memory:
    max-messages: 10
